tottms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('coreApp.urls')),
    path('user/', include(('userApp.urls', 'userApp'), namespace='userApp')),
    path('officer/', include('officersApp.urls')),
    path('transfer/', include('transferApp.urls')),
    path('location/', include('locationApp.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]
urlpatterns += staticfiles_urlpatterns()

transferApp/urls.py
# userApp/urls.py
from django.urls import path
from .views import teacher_application_view, get_districts

urlpatterns = [
    # Your existing URLs...
    path('application/', teacher_application_view, name='teacher_application'),
    # Add this to your Django urls.py
    path('get-districts/', get_districts, name='get_districts'),

]

transferApp/models.py
from django.db import models
from locationApp.models import Region, District
from userApp.models import Teacher, EducationOfficer, TamisemiUser, DistrictExecutiveDirector, UtumishiUser, EducationLevel, Course, WorkerGrade, Subject, SchoolLevel, School
from django.db import models
from django.contrib.auth import get_user_model

class TransferReasons(models.Model):
    reason = models.CharField(max_length=100, null=True)
    
    def __str__(self) -> str:
        return self.reason
    
# userApp/models.py



class Application(models.Model):
    APPLICANT_CHOICES = [
        ('teacher', 'Exchange Transfer Application'),
        ('teacher', 'Direct Transfer Application'),
    ]

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    applicant_type = models.CharField(max_length=10, choices=APPLICANT_CHOICES)
    reason = models.TextField()
    supporting_document = models.FileField(upload_to='supporting_documents/')
    submitted_at = models.DateTimeField(auto_now_add=True)

    # Fields specific to Teacher Application
    education_level = models.ForeignKey(EducationLevel, on_delete=models.CASCADE, null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    grade = models.ForeignKey(WorkerGrade, on_delete=models.CASCADE, null=True)
    subjects_taught = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True)
    school_level = models.ForeignKey(SchoolLevel, on_delete=models.CASCADE, null=True)
    school = models.ForeignKey(School, on_delete=models.CASCADE, null=True, blank=True)

    # Fields specific to Transfer Application
    region_from = models.ForeignKey(Region, on_delete=models.CASCADE, related_name='transfer_application_region_from', null=True)
    district_from = models.ForeignKey(District, on_delete=models.CASCADE, related_name='transfer_application_district_from', null=True)
    region_to = models.ForeignKey(Region, on_delete=models.CASCADE, related_name='transfer_application_region_to', null=True)
    district_to = models.ForeignKey(District, on_delete=models.CASCADE, related_name='transfer_application_district_to', null=True)
    is_confirmed = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.get_applicant_type_display()} Application - {self.user.username} - {self.submitted_at}"

    


class TransferVerification(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    verified_officer = models.ForeignKey(EducationOfficer, on_delete=models.CASCADE)
    verified_ded = models.ForeignKey(DistrictExecutiveDirector, on_delete=models.CASCADE)
    verification_date = models.DateTimeField(auto_now_add=True)
    is_verified = models.BooleanField(default=False)

class TransferSubmission(models.Model):
    application = models.OneToOneField(Application, on_delete=models.CASCADE)
    submitted_by = models.ForeignKey(EducationOfficer, on_delete=models.CASCADE)
    submission_date = models.DateTimeField(auto_now_add=True)

class TamisemiConfirmation(models.Model):
    application = models.OneToOneField(Application, on_delete=models.CASCADE)
    confirmed_by = models.ForeignKey(TamisemiUser, on_delete=models.CASCADE)
    confirmation_date = models.DateTimeField(auto_now_add=True)

class UtumishiTransfer(models.Model):
    application = models.OneToOneField(Application, on_delete=models.CASCADE)
    transferred_by = models.ForeignKey(UtumishiUser, on_delete=models.CASCADE)
    transfer_date = models.DateTimeField(auto_now_add=True)
    salary_transfer_complete = models.BooleanField(default=False)

transferApp/forms.py
# transferApp/forms.py
from django import forms
from .models import Application

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['region_from', 'district_from', 'region_to', 'district_to',  'reason', 'supporting_document']

transferApp/views.py
from django.shortcuts import render, redirect
from .forms import ApplicationForm
from django.http import JsonResponse
from locationApp.models import District

def teacher_application_view(request):
    if request.method == 'POST':
        form = ApplicationForm(request.POST, request.FILES)
        if form.is_valid():
            # Save the form and do any additional processing
            form.save()
            return redirect('application_success')  # Redirect to a success page
    else:
        form = ApplicationForm()

    return render(request, 'transferApp/transferApplication.html', {'form': form})


def get_districts(request):
    region_id = request.GET.get('region_id')
    # Perform a query to get the districts based on the region_id
    districts = District.objects.filter(region_id=region_id).values('id', 'name')
    return JsonResponse({'districts': list(districts)})

transferApp/templates/transferApp/transferApplication.html
 {% extends "coreApp/base.html" %} 




 {% block page_header %}
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
{% endblock page_header %}

{% load bootstrap_icons %}
  
<script>
    $(document).ready(function () {
        // Fetch districts based on the selected region for district_from
        $('#id_region_from').change(function () {
            var selectedRegion = $(this).val();
            fetchDistricts(selectedRegion, 'id_district_from');
        });
    
        // Fetch districts based on the selected region for district_to
        $('#id_region_to').change(function () {
            var selectedRegion = $(this).val();
            fetchDistricts(selectedRegion, 'id_district_to');
        });
    
        // Function to fetch districts based on the selected region
        function fetchDistricts(regionId, districtFieldId) {
            // Use AJAX request to fetch districts
            $.ajax({
                url: '/get-districts/',
                data: { region_id: regionId },
                success: function (data) {
                    // Clear existing options
                    $('#' + districtFieldId).empty();
                    
                    // Add "Select All" option if needed
                    // ...
    
                    // Add fetched districts as options
                    $.each(data.districts, function (key, value) {
                        $('#' + districtFieldId).append($('<option></option>').attr('value', key).text(value));
                    });
                },
                error: function (xhr, status, error) {
                    // Handle error
                    console.error(xhr, status, error);
                }
            });
        }
    });
</script> 
{% block content %}

    <div class="container p-5 my-2 border bg-white d-flex justify-content-center align-items-center" style="max-width: 40rem;">
        <div>
            <h2>Teacher Application</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Submit Application</button>
            </form>
        </div>
    </div>

      
    

{% endblock %}