tottms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('coreApp.urls')),
    path('user/', include(('userApp.urls', 'userApp'), namespace='userApp')),
    path('officer/', include('officersApp.urls')),
    path('transfer/', include('transferApp.urls')),
    path('location/', include('locationApp.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]
urlpatterns += staticfiles_urlpatterns()

userApp/urls.py
# from django.urls import path, include


# from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
# from django.urls import path

# app_name = 'userApp'
# urlpatterns = [
#     # ... other URL patterns ...
#     path('login/', LoginView.as_view(template_name='login.html'), name='login'),
#     # ... other URL patterns ...
#       # ... other URL patterns ...
#     path('password_reset/', PasswordResetView.as_view(template_name='password_reset_form.html'), name='password_reset'),
#     path('password_reset/done/', PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
#     path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
#     path('reset/done/', PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
#     # ... other URL patterns ...
# ]
from django.urls import path
from .views import CustomLoginView, CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView
from .views import CustomSignupView, CustomPasswordResetConfirmView, Teachers_list, profile_view 


urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('profile/', profile_view, name='user_profile'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('signup/', CustomSignupView.as_view(), name='signup'),
    path('teachers/', Teachers_list, name='teachers'),
    # path('teachers/<int:teacher_id>/', Teachers_list, name='teachers'),
    
    
]

userApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.contrib.auth.hashers import make_password
from django.utils import timezone
from django.core.validators import MaxLengthValidator, MinLengthValidator
from locationApp.models import SchoolLevel, Region, District, School

class Course(models.Model):
    name = models.CharField(max_length=100)
    coursecode=models.IntegerField( unique=True,null=True)
    def __str__(self):
        return self.name

class Subject(models.Model):
    name = models.CharField(max_length=100)
    subjectcode=models.IntegerField( unique=True,null=True)

    def __str__(self):
        return self.name
    
# the WorkerGrade model
    
class WorkerGrade(models.Model):
    grade = models.CharField(max_length=100)
    
    def __str__(self) -> str:
        return self.grade

# the SalaryScale model
    
class SalaryScale(models.Model):
    scale= models.CharField(max_length=50,null=True)
    amount = models.IntegerField(null=True)
    
    def __str__(self) -> str:
        return self.scale

#the gender model

class Gender(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self) -> str:
        return self.name
    
class KindOfOfficer(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self) -> str:
        return self.name

#the position model
    
class Position(models.Model):
    name = models.CharField(max_length=110)
    def __str__(self) -> str:
        return self.name


class EducationLevel(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class CustomUser(AbstractUser):
    # Add any additional user fields here, if needed
    
    fname = models.CharField(max_length=100)
    mname = models.CharField(max_length=100)
    lname = models.CharField(max_length=100)
    gender = models.ForeignKey(Gender,on_delete=models.CASCADE,null=True)
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(unique=True, )
    phone = models.CharField(max_length=100)
    birthdate = models.DateTimeField(null=True)
    nin = models.CharField(max_length=20, null=True, blank=True,
    validators=[
        MaxLengthValidator(limit_value=20),
        MinLengthValidator(limit_value=20),
    ])
    image = models.ImageField(max_length=255, upload_to='images/', null=True, blank=True)
    position = models.ForeignKey(Position,on_delete=models.CASCADE, null=True)
    is_teacher = models.BooleanField(default=False)
    is_education_officer = models.BooleanField(default=False)
    is_ded = models.BooleanField(default=False)
    is_tamisemi = models.BooleanField(default=False)
    is_utumishi = models.BooleanField(default=False)
    password = models.CharField(max_length=180, null=True, blank=True)  # You should hash and salt passwords
    created_at = models.DateTimeField(auto_now_add=True)
    retirement = models.DateTimeField(null=True)
    updated_at = models.DateTimeField(auto_now=True)
    groups = models.ManyToManyField(Group, related_name='custom_user_groups')
    user_permissions = models.ManyToManyField(Permission, related_name='custom_user_permissions')
    
    def save(self, *args, **kwargs):
        if self.password and not self.password.startswith('bcrypt_sha256$'):
           self.password = make_password(self.password)

        if self.birthdate and self.created_at:
            years_of_service = (self.created_at - self.birthdate).days / 365
            retirement_age = 60
            retirement_date = self.birthdate + timezone.timedelta(days=int((retirement_age - years_of_service) * 365))
            self.retirement = retirement_date

        super().save(*args, **kwargs)
    
   

def __str__(self):
    return f"{self.lname} - {self.fname} {self.username}"

    
    pass

class Teacher(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    education_level = models.ForeignKey(EducationLevel, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    grade = models.ForeignKey(WorkerGrade, on_delete=models.CASCADE, null=True)
    subjects_taught = models.ManyToManyField(Subject, blank=True)
    region = models.ForeignKey(Region, on_delete=models.CASCADE, null=True)
    district = models.ForeignKey(District, on_delete=models.CASCADE, null=True)
    school_level = models.ForeignKey(SchoolLevel, on_delete=models.CASCADE)
    school = models.ForeignKey(School, on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return f"{self.user},{self.school_level},{self.region} {self.district}"
    # Add teacher-specific fields here

class Supervisor(models.Model):
    headofschool = models.ForeignKey(Teacher, on_delete = models.CASCADE, null=True, blank=True)
     
    

class EducationOfficer(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    type = models.ForeignKey(KindOfOfficer, on_delete=models.CASCADE,null=True)
    region = models.ForeignKey(Region, on_delete=models.CASCADE, null=True)
    district = models.ForeignKey(District, on_delete=models.CASCADE, null=True)
    # Add education officer-specific fields here
    
class DistrictExecutiveDirector(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    region = models.ForeignKey(Region, on_delete=models.CASCADE, null=True)
    district = models.ForeignKey(District, on_delete=models.CASCADE, null=True)
    
class TamisemiUser(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    # Add Tamisemi-specific fields here

class UtumishiUser(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    # Add Utumishi-specific fields here

userApp/forms.py
# userApp/forms.py
from django import forms

class SignupForm(forms.Form):
    check_number = forms.CharField(max_length=100, label='Check Number')

userApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
# userApp/views.py
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_decode
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.views import PasswordContextMixin
from django.views.generic.edit import FormView
from django.contrib.auth.views import LoginView
from .forms import SignupForm
from datetime import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from django.contrib.auth.decorators import login_required
from .models import Teacher,CustomUser
from locationApp.models import SchoolLevel, School


class CustomLoginView(LoginView):
    template_name = 'userApp/login.html'
    # redirect_authenticated_user = True

    def form_valid(self, form):
        # Call the parent class's form_valid method to perform the default login actions
        response = super().form_valid(form)

        # Customize the redirection based on the user's group
        user = self.request.user
        if user.is_authenticated:
            if user.groups.filter(name='Teachers').exists():
                # Redirect teachers to the teacher profile URL
                return redirect('user_profile')
            elif user.groups.filter(name='Educationofficers').exists():
                # Redirect Education officers to the Education officer profile URL
                return redirect('user_profile')
            elif user.groups.filter(name='Districtofficers').exists():
                # Redirect District officers to the District officer profile URL
                return redirect('user_profile')
            elif user.groups.filter(name='Tamisemi').exists():
                # Redirect Tamisemi users to the Tamisemi profile URL
                return redirect('tamisemi_profile')
            elif user.groups.filter(name='Utumishi').exists():
                # Redirect Utumishi users to the Utumishi profile URL
                return redirect('user_profile')
            else:
                # Redirect to the default profile URL
                return redirect('user_profile')

        return response

 
# views.py



# @login_required
def profile_view(request):
    user = request.user
    is_teacher = user.groups.filter(name='Teachers').exists()
    is_education_officer = user.groups.filter(name='Educationofficers').exists()
    is_district_officer = user.groups.filter(name='Districtofficers').exists()
    is_tamisemi = user.groups.filter(name='Tamisemi').exists()
    is_utumishi = user.groups.filter(name='Utumishi').exists()
    
    current_time = datetime.now().time()

    # Determine the time of day
    if current_time.hour < 12:
        greeting = "Good morning"
    elif 12 <= current_time.hour < 18:
        greeting = "Good afternoon"
    else:
        greeting = "Good evening"

    context = {
        'greeting': f'{greeting}, {request.user.username}',
        'user': user,
        'is_teacher': is_teacher,
        'is_education_officer': is_education_officer,
        'is_district_officer': is_district_officer,
        'is_tamisemi': is_tamisemi,
        'is_utumishi': is_utumishi,
    }

    return render(request, 'userApp/profile.html', context)

# Password reset views
class CustomPasswordResetView(PasswordResetView):
    template_name = 'password_reset_form.html'
    email_template_name = 'password_reset_email.html'
    success_url = reverse_lazy('password_reset_done')

class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'password_reset_done.html'

class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'password_reset_confirm.html'
    success_url = reverse_lazy('password_reset_complete')

class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'password_reset_complete.html'
    

User = get_user_model()

class CustomPasswordResetConfirmView(PasswordContextMixin, FormView):
    form_class = SetPasswordForm
    success_url = '/user/login/'
    template_name = 'userApp/signup_confirm.html'

    def get_user(self, uidb64):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            return User._default_manager.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            return None

    def get(self, request, *args, **kwargs):
        uidb64 = kwargs['uidb64']
        user = self.get_user(uidb64)
        if user is None or not default_token_generator.check_token(user, kwargs['token']):
            return self.render_to_response(self.get_context_data())
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        uidb64 = self.kwargs['uidb64']
        user = self.get_user(uidb64)
        if user is not None and default_token_generator.check_token(user, self.kwargs['token']):
            form.save()
            return super().form_valid(form)
        return self.form_invalid(form)

class CustomSignupView(FormView):
    template_name = 'userApp/signup.html'
    form_class = SignupForm

    def form_valid(self, form):
        check_number = form.cleaned_data['check_number']
        user = get_object_or_404(User, username=check_number)
        return render(self.request, 'userApp/signup_confirm.html', {'user': user})

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))
    
    
    
    
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from .models import Teacher, SchoolLevel

def Teachers_list(request):
    # Get the selected school level from the query parameters
    selected_school_level = request.GET.get('school_level')

    # Get all school levels for dropdown
    all_school_levels = SchoolLevel.objects.all()

    # Get all teachers or filter by selected school level
    if selected_school_level:
        teachers = Teacher.objects.filter(school_level__levelName=selected_school_level)
    else:
        teachers = Teacher.objects.all()

    # Count total teachers, primary teachers, and secondary teachers
    total_teachers_count = Teacher.objects.count()
    primary_teachers_count = Teacher.objects.filter(school_level__levelName='Primary').count()
    secondary_teachers_count = Teacher.objects.filter(school_level__levelName='Secondary').count()

    # Pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(teachers, 10)  # Show 10 teachers per page
    try:
        teachers = paginator.page(page)
    except PageNotAnInteger:
       teachers = paginator.page(1)
    except EmptyPage:
       teachers = paginator.page(paginator.num_pages)

    return render(request, 'userApp/teacherlist.html', {
        'teachers': teachers,
        'all_school_levels': all_school_levels,
        'selected_school_level': selected_school_level,
        'total_teachers_count': total_teachers_count,
        'primary_teachers_count': primary_teachers_count,
        'secondary_teachers_count': secondary_teachers_count,
    })



# Other views...

# def Teachers_list(request):
#     # Get the selected school level from the query parameters
#     selected_school_level = request.GET.get('school_level')

#     # Get all school levels for dropdown
#     all_school_levels = SchoolLevel.objects.all()

#     # Get all schools or filter by selected school level
#     if selected_school_level:
#         teachers = Teacher.objects.filter(School_level__levelName=selected_school_level)
#     else:
#         teachers = Teacher.objects.all()

#     # Count total Teachers, primary schools, and secondary schools
#     total_teachers_count = Teacher.objects.count()
#     primary_teachers_count = Teacher.objects.filter(School_level__levelName='Primary').count()
#     secondary_teachers_count = Teacher.objects.filter(School_level__levelName='Secondary').count()

#     # Pagination
#     page = request.GET.get('page', 1)
#     paginator = Paginator(teachers, 10)  # Show 10 schools per page
#     try:
#         teachers = paginator.page(page)
#     except PageNotAnInteger:
#        teachers = paginator.page(1)
#     except EmptyPage:
#        teachers = paginator.page(paginator.num_pages)

#     return render(request, 'userApp/teacherlist.html', {
#         'teachers': teachers,
#         'all_school_levels': all_school_levels,
#         'selected_school_level': selected_school_level,
#         'total_schools_count': total_teachers_count,
#         'primary_schools_count': primary_teachers_count,
#         'secondary_schools_count': secondary_teachers_count,
#     })

userApp/templates/userApp/ded.html
{% load bootstrap_icons %}
<div class="container p-5 my-5 border">

    <div class="row">          
            <div class="col-md-4">  
                  <h2>Personal Information</h2>
                  <p>{% bs_icon 'person-check'%}First Name: {{  profile_view.user.first_name }}</p>
                  <p>{% bs_icon 'person-check'%}Middle Name: {{ profile_view.user.middle_name }}</p>
                  <p>{% bs_icon 'person-check'%}Last Name: {{ profile_view.user.last_name }}</p>
                  <p>{% bs_icon 'gender-ambiguous'%}Gender: {{ profile_view.user.teacherprofile.gender }}</p>
                  <p>{% bs_icon 'envelope-at'%}Email: {{ profile_view.user.email }}</p>
                  <p>{% bs_icon 'phone'%} Phone: {{ profile_view.user.teacherprofile.phone }}</p>
                  <p>{% bs_icon 'cake2'%} Birthdate: {{ profile_view.user.teacherprofile.birthdate }}</p>
                  <p>{% bs_icon 'person-vcard'%}NIN: {{ profile_view.user.teacherprofile.nin }}</p>
            </div>
    
            <div class="col-md-4">
              <h2>Education Information</h2>
              <p>{% bs_icon 'mortarboard'%} Education level:</p>
              <p>{% bs_icon 'book'%} Course:</p>
              <p>{% bs_icon 'pencil'%} Subject:</p>
              <p>{% bs_icon 'stack'%} Specialization:</p>
            </div>
    
            <div class="col-md-4">
                  <h2>Work Information</h2>
                  <p>{% bs_icon 'at'%}Position: {{ profile_view.check_number }}</p>
                  <p>{% bs_icon 'braces'%}Type: {{ profile_view.type }}</p>
                  <p>{% bs_icon 'key'%}Check Number: {{ profile_view.check_number }}</p>
                  <p>{% bs_icon 'calendar'%}Start Date: {{ profile_view.start_date }}</p>
                  <p>{% bs_icon 'calendar3-range'%}Retire Date: {{ profile_view.retirement }}</p>
                  <p>{% bs_icon 'calendar3-range'%}Salary Scale: {{ profile_view.expected_retire_date }}</p>
                  <p>{% bs_icon 'globe-europe-africa'%}Region: {{ profile_view.region }}</p>
                  <p>{% bs_icon 'globe-europe-africa'%}District: {{ profile_view.district }}</p>
                  
            </div>

</div>

userApp/templates/userApp/login.html
{% extends "coreApp/base.html" %}
{% load static%}

{% block page_header%}
<style>
    
      
</style>

{%endblock page_header%}

{% block content %}


    <div class="container p-5 my-2 border bg-white d-flex justify-content-center align-items-center" style="max-width: 40rem;">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center bg-dark text-white">
                    <h1>Login to TOTTMS</h1>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form }}
                        <br></br>
                        <div class=" d-flex justify-content-center align-items-center">
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                        
                        <div class="mb-3">
                            <span class="text-muted">Don't have an account? </span>
                            <a href="/user/signup" class="text-decoration-none">Sign up</a> |
                            <span class="text-muted">Forgot password? </span>
                            <a href="/reset-password" class="text-decoration-none">Reset password</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

userApp/templates/userApp/officer.html
{% load bootstrap_icons %}
<div class="container p-5 my-5 border">

    <div class="row">          
            <div class="col-md-4">  
                  <h2>Personal Information</h2>
                  <p>{% bs_icon 'person-check'%}First Name: {{  profile_view.user.first_name }}</p>
                  <p>{% bs_icon 'person-check'%}Middle Name: {{ profile_view.user.middle_name }}</p>
                  <p>{% bs_icon 'person-check'%}Last Name: {{ profile_view.user.last_name }}</p>
                  <p>{% bs_icon 'gender-ambiguous'%}Gender: {{ profile_view.user.teacherprofile.gender }}</p>
                  <p>{% bs_icon 'envelope-at'%}Email: {{ profile_view.user.email }}</p>
                  <p>{% bs_icon 'phone'%} Phone: {{ profile_view.user.teacherprofile.phone }}</p>
                  <p>{% bs_icon 'cake2'%} Birthdate: {{ profile_view.user.teacherprofile.birthdate }}</p>
                  <p>{% bs_icon 'person-vcard'%}NIN: {{ profile_view.user.teacherprofile.nin }}</p>
            </div>
    
            <div class="col-md-4">
              <h2>Education Information</h2>
              <p>{% bs_icon 'mortarboard'%} Education level:</p>
              <p>{% bs_icon 'book'%} Course:</p>
              <p>{% bs_icon 'pencil'%} Subject:</p>
              <p>{% bs_icon 'stack'%} Specialization:</p>
            </div>
    
            <div class="col-md-4">
                  <h2>Work Information</h2>
                  <p>{% bs_icon 'at'%}Position: {{ profile_view.check_number }}</p>
                  <p>{% bs_icon 'braces'%}Type: {{ profile_view.type }}</p>
                  <p>{% bs_icon 'key'%}Check Number: {{ profile_view.check_number }}</p>
                  <p>{% bs_icon 'calendar'%}Start Date: {{ profile_view.start_date }}</p>
                  <p>{% bs_icon 'calendar3-range'%}Retire Date: {{ profile_view.retirement }}</p>
                  <p>{% bs_icon 'calendar3-range'%}Salary Scale: {{ profile_view.expected_retire_date }}</p>
                  <p>{% bs_icon 'globe-europe-africa'%}Region: {{ profile_view.region }}</p>
                  <p>{% bs_icon 'globe-europe-africa'%}District: {{ profile_view.district }}</p>
                  
            </div>

</div>

userApp/templates/userApp/profile.html
{% extends "coreApp/base.html" %}
{% block page_header%}
{% include 'coreApp/navbar.html'%}
{%endblock page_header%}
{% load bootstrap_icons %}
{% block content %}
<div class="container p-5 my-5 border bg-white">
              <div class = 'row'>
                  <div class = 'col-md-4'>
                       <img src="{{ user.teacherprofile.image.url }}" alt="Profile Picture" class="rounded-circle" width="150" height="150">
                       
                  </div>
                  <div class = 'col-md-6' >
                       <h2>Welcome to your profile {{ user.username }}</h2>
                       <p>{{ greeting }}</p>
                    
                  </div>
                
              </div>
   
        
    {% include 'userApp/teacher.html'%}

    {% if is_teacher %}
         {% include 'userApp/teacher.html'%}
    {% elif is_education_officer %}
         {% include 'userApp/officer.html'%}
    {% elif is_district_officer %}
         {% include 'userApp/ded.html'%}
    {% elif is_tamisemi %}
         {% include 'userApp/tamisemi.html'%}
    {% elif is_utumishi %}
         {% include 'userApp/utumishi.html'%}
    {% endif %}
</div>
{% endblock %}

userApp/templates/userApp/signup.html
<!-- userApp/templates/userApp/signup.html -->
{% extends "coreApp/base.html" %}
{% block page_header%}
<style>
      
</style>

{%endblock page_header%}

{% block content %}

<div class="container p-5 my-2 border bg-white  justify-content-center align-items-center" style="max-width: 40rem;">
        <div class="card-header text-center bg-dark text-white">
            <h1>Signup to TOTTMS</h1>
        </div>
    <div class= "card-body">
            <form method="post" class="mt-3">
                {% csrf_token %}
                {{ form.as_p }}
              
                        <div class=" d-flex justify-content-center align-items-center">
                            <button type="submit" class="btn btn-primary">Search</button>
                        </div>
                
                        <div class="mb-3">
                            <span class="text-muted">Already have an account? </span>
                            <a href="/user/login" class="text-decoration-none">Login</a> |
                            <span class="text-muted">Forgot password? </span>
                            <a href="/reset-password" class="text-decoration-none">Reset password</a>
                        </div>
            </form>
    </div> 
</div>

{% endblock %}

userApp/templates/userApp/teacherlist.html
{% extends "coreApp/base.html" %}
{% load static %}

{% block page_header %}
<style>
/* Add any custom styles if needed */
</style>
{% endblock page_header %}

{% block content %}
<body>
    <div class="container bg-white">
        <h1 class="text-center">Teachers List</h1>

        <!-- Dropdown for selecting school levels -->
        <form method="get" action="{% url 'userApp:teachers' %}" class="mb-3">
            <label for="school_level" class="form-label">Filter by School Level</label>
            <select name="school_level" id="school_level" class="form-select">
                <option value="">All</option>
                {% for level in all_school_levels %}
                    <option value="{{ level.levelName }}" {% if selected_school_level == level.levelName %}selected{% endif %}>{{ level.levelName }}</option>
                {% endfor %}
            </select>
            <button class="btn btn-dark" type="submit">Filter</button>
        </form>

        <div class="container mt-3">
            <div class="mb-3">
                <p>Total Teachers: {{ total_teachers_count }}</p>
                <p>Primary Teachers: {{ primary_teachers_count }}</p>
                <p>Secondary Teachers: {{ secondary_teachers_count }}</p>
            </div>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>S/N</th>
                            <th>Name</th>
                            <th>CheckNo</th>
                            <th>Education</th>
                            <th>Course</th>
                            <th>Subjects</th>
                            <th>Region</th>
                            <th>District</th>
                            <th>School</th>
                            <th>Level</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for teacher in teachers %}
                            <tr>
                                <td>{{ teacher.id }}</td>
                                <td>{{ teacher.user.fname }} {{ teacher.user.lname }}</td>
                                <td>{{ teacher.user.username }}</td>
                                <td>{{ teacher.education_level }}</td>
                                <td>{{ teacher.course }}</td>
                                <td>
                                    {% for subject in teacher.subjects_taught.all %}
                                        {{ subject.name }}
                                        {% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                </td>
                                <td>{{ teacher.region.name }}</td>
                                <td>{{ teacher.district.name }}</td>
                                <td>{{ teacher.school.name }}</td>
                                <td>{{ teacher.school_level.levelName }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Pagination links -->
        <div class="pagination d-flex justify-content-center mt-3">
            <span class="step-links">
                {% if teachers.has_previous %}
                <div class="btn-group">
                    <a class="btn btn-dark type=button"  href="?page=1">&laquo; first</a>
                    <a class="btn btn-dark type=button"  href="?page={{ teachers.previous_page_number }}">previous</a>
                 </div>
                {% endif %}

                <span  class=" current btn btn-dark type=button">
                    Page {{ teachers.number }} of {{ teachers.paginator.num_pages }}
                </span>

                {% if teachers.has_next %}
                <div class="btn-group">
                    <a class="btn btn-dark type=button" href="?page={{ teachers.next_page_number }}">next</a>
                    <a class="btn btn-dark type=button"  href="?page={{ teachers.paginator.num_pages }}">last &raquo;</a>
                 </div>
                {% endif %}
            </span>
        </div>
    </div>
</body>
{% endblock %}