locationApp/urls.py
from django.urls import path, include



from .views import school_list_view, region_list

app_name = 'locationApp'
# urls.py

urlpatterns = [
    path('schools/', school_list_view, name='schools'),
    path('regions/', region_list, name='regions'),
]

tottms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('coreApp.urls')),
    path('user/', include(('userApp.urls', 'userApp'), namespace='userApp')),
    path('officer/', include('officersApp.urls')),
    path('transfer/', include('transferApp.urls')),
    path('location/', include('locationApp.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]
urlpatterns += staticfiles_urlpatterns()

locationApp/models.py
from django.db import models




class SchoolLevel(models.Model): 
    levelName = models.CharField(max_length=100,null=True)
    subvote = models.IntegerField(null=True)
    def __str__(self):
        return self.levelName
    
class Region(models.Model):
    name = models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return self.name

# the District model
class District(models.Model):
    name = models.CharField(max_length=100)
    votecode = models.CharField(max_length=20, unique=True)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.name}, {self.region}"

# the School model
class School(models.Model):
    registration = models.IntegerField( default = 1000, null=True, blank=True)
    name = models.CharField(max_length=200)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    School_level = models.ForeignKey(SchoolLevel, on_delete=models.CASCADE)
    

    def __str__(self):
        return f"{self.name},{self.School_level},{self.region} {self.district}"

locationApp/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import School, SchoolLevel, Region, District
# from userApp.models import Supervisor

def school_list_view(request):
    # Get the selected school level from the query parameters
    selected_school_level = request.GET.get('school_level')

    # Get all school levels for dropdown
    all_school_levels = SchoolLevel.objects.all()

    # Get all schools or filter by selected school level
    if selected_school_level:
        schools = School.objects.filter(School_level__levelName=selected_school_level)
    else:
        schools = School.objects.all()

    # Count total schools, primary schools, and secondary schools
    total_schools_count = School.objects.count()
    primary_schools_count = School.objects.filter(School_level__levelName='Primary').count()
    secondary_schools_count = School.objects.filter(School_level__levelName='Secondary').count()

    # Pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(schools, 10)  # Show 10 schools per page
    try:
        schools = paginator.page(page)
    except PageNotAnInteger:
        schools = paginator.page(1)
    except EmptyPage:
        schools = paginator.page(paginator.num_pages)

    return render(request, 'locationApp/schools.html', {
        'schools': schools,
        'all_school_levels': all_school_levels,
        'selected_school_level': selected_school_level,
        'total_schools_count': total_schools_count,
        'primary_schools_count': primary_schools_count,
        'secondary_schools_count': secondary_schools_count,
    })



def region_list(request):
    regions = Region.objects.all()
    return render(request, 'locationApp/region.html', {'regions': regions})

locationApp/templates/locationApp/region.html
 <!-- region.html -->

{% extends 'coreApp/base.html' %}

{% block content %}
  <div class="container mt-3">
    <div class="bg-white">
    <h1>Region List</h1>
    </div>
    <div class="row">
      {% for region in regions %}
        <div class="col-md-4 mb-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{ region.name }}</h5>
              <a type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#myModal"> view districts</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>

  <!-- The Modal -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
  
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">{{region.name}} all district council</h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>
  
        <!-- Modal body -->
        <div class="modal-body">
          Modal body..
        </div>
  
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
        </div>
  
      </div>
    </div>
  </div>
{% endblock %} 

locationApp/templates/locationApp/schools.html
<!-- schools.html -->


<!-- schools.html -->

{% extends "coreApp/base.html" %}
{% load static %}

{% block page_header %}
<style>
</style>
{% endblock page_header %}

{% block content %}
<body>
    <div class="container justify-content-center align-items-center bg-white">
        <h1>School List</h1>

        <!-- Dropdown for selecting school levels -->
        <form method="get" action="{% url 'locationApp:schools' %}">
            <label for="school_level">Filter by School Level</label>
            <select name="school_level" id="school_level">
                <option value="">All</option>
                {% for level in all_school_levels %}
                    <option value="{{ level.levelName }}" {% if selected_school_level == level.levelName %}selected{% endif %}>{{ level.levelName }}</option>
                {% endfor %}
            </select>
            <button class="btn btn-dark type=button" type="submit">Filter</button>
        </form>

        <div class="container mt-3 bg-white ">
            <div>
            <p>Total Schools: {{ total_schools_count }}</p> 
          
            {% comment %} <p>Primary Schools: {{ primary_schools_count }}</p>
            
            <p>Secondary Schools: {{ secondary_schools_count }}</p> {% endcomment %}
            </div>
            <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>S/N</th>
                        <th>Registration</th>
                        <th>School Name</th>
                        <th>School Level</th>
                        <th>District</th>
                        <th>Region</th>
                    </tr>
                </thead>
                <tbody>
                    {% for school in schools %}
                        <tr>
                            <td>{{ school.id }}</td>
                            <td>S{{ school.registration }}</td>
                            <td>{{ school.name }}</td>
                            <td>{{ school.School_level.levelName }}</td>
                            <td>{{ school.district.name }}</td>
                            <td>{{ school.region.name }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        </div>

        <!-- Pagination links -->
        <div class="pagination">
            <span class="step-links">
                {% if schools.has_previous %}
                <div class="btn-group">
                    <a class="btn btn-dark type=button"  href="?page=1">&laquo; first</a>
                    <a class="btn btn-dark type=button"  href="?page={{ schools.previous_page_number }}">previous</a>
                 </div>
                {% endif %}

                <span  class=" current btn btn-dark type=button">
                    Page {{ schools.number }} of {{ schools.paginator.num_pages }}
                </span>

                {% if schools.has_next %}
                <div class="btn-group">
                    <a class="btn btn-dark type=button" href="?page={{ schools.next_page_number }}">next</a>
                    <a class="btn btn-dark type=button"  href="?page={{ schools.paginator.num_pages }}">last &raquo;</a>
                 </div>
                {% endif %}
            </span>
        </div>
    </div>
</body>
{% endblock %}